apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tvxe
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/karthik-jk-tenant/my-app/devfile-sample-tvxe@sha256:a92cfb83279d3674854508db5909cec905e02db6154e603892b57d9b1a769e09
        name: my-nodejs
        resources: {}
status: {}
